server:
  port: 17000
spring:
  application:
    name: pcc-ss
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/pcc_ss
      driver-class-name: org.mariadb.jdbc.Driver
      username: pcc
      password: pcc123
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: none
    show-sql: 'true'

mybatis:
  mapper-locations:
    - classpath:/egovframework/mapper/let/**/*_mariadb.xml"
    - classpath:/mappers/**/*.xml
  type-aliases-package: com.promisepeople.ss.fthcheck.mapper
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org:
      springframework:
        security:
          web: trace

#org:
#  promisepeoples:
#    fthchck:
#      path: upload
